using System;
using System.Collections.Generic;
using System.Linq;
using FluentValidation.Results;
using Microsoft.AspNetCore.Identity;

namespace Application.Common.Exceptions
{
    public class ValidationException : Exception
    {
        public ValidationException()
            : base("One or more validation failures have occurred.")
        {
            Failures = new Dictionary<string, string[]>();
        }

        public ValidationException(IEnumerable<ValidationFailure> failures)
            : this()
        {
            var failureGroups = failures
                .GroupBy(e => e.PropertyName, e => e.ErrorMessage);

            foreach (var failureGroup in failureGroups)
            {
                var propertyName = failureGroup.Key;
                var propertyFailures = failureGroup.ToArray();

                Failures.Add(propertyName, propertyFailures);
            }
        }

        public ValidationException(IdentityResult identityResult)
            : this()
        {
            Failures = identityResult.Errors
                .GroupBy(e => e.Code)
                .ToDictionary(g => g.Key
                    , g => g.Select(g => g.Description)
                        .ToArray());
        }

        public ValidationException(params string[] errors)
            : this()
        {
            if (errors != null)
            {
                Failures.Add(string.Empty, errors);
            }
        }

        public IDictionary<string, string[]> Failures { get; }
    }
}